version: 2

jobs:
  build:
    working_directory: ~/circlecitest
    docker:
     - image: circleci/android:api-26-alpha
    environment:
      GRADLE_OPTS: -Xmx4g
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run:
          name: Download dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
          paths:
            - ~/.gradle
      - run:
          name: Run unit tests
          command: ./gradlew lint test
      - run:
          name: Deploy app to Fabric
          command: ./gradlew assembleRelease crashlyticsUploadDistributionDebug --stacktrace
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:
          path: app/build/reports
          destination: reports